#!/usr/bin/env bash
set -e
if [ -e "hello" ]; then
  mv hello ..
fi
make BR2_EXTERNAL="$(pwd)/../hello" qemu_x86_64_defconfig
echo 'BR2_PACKAGE_HELLO=y' >> .config
env -u LD_LIBRARY_PATH make BR2_JLEVEL="$(($(nproc) - 2))"
qemu-system-x86_64 -M pc -kernel output/images/bzImage -drive file=output/images/rootfs.ext2,if=virtio,format=raw -append root=/dev/vda -net nic,model=virtio -net user
