#!/usr/bin/env bash
set -e
unset LD_LIBRARY_PATH
make qemu_aarch64_virt_defconfig
printf "
# Key options.
BR2_PACKAGE_HELLO=y
BR2_PACKAGE_LIBDRM=y
BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES=\"kernel_config_fragment\"

# Less key.
BR2_CCACHE=y
BR2_PACKAGE_HOST_QEMU=y
BR2_PACKAGE_HOST_QEMU_LINUX_USER_MODE=n
BR2_PACKAGE_HOST_QEMU_SYSTEM_MODE=y
BR2_PACKAGE_HOST_QEMU_VDE2=y
" >> .config
make olddefconfig
time make BR2_JLEVEL="$(nproc)" HOST_QEMU_OPTS='--enable-sdl --with-sdlabi=2.0' hello-reconfigure linux-reconfigure all
./output/host/usr/bin/qemu-system-aarch64 -M virt -cpu cortex-a57 -smp 1 -kernel output/images/Image -append "root=/dev/vda console=ttyAMA0" -netdev user,id=eth0 -device virtio-net-device,netdev=eth0 -drive file=output/images/rootfs.ext4,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -device virtio-gpu-pci -serial mon:stdio "$@"
